### ISSUE TITLE
Error: Could not find source file 

### ISSUE THREAD

**Issue by fsargent** [JoshuaKGoldberg/TypeStat#1127]
### Overview

Error on terminal:

There were a few more of them. Started on wave 6. 

<img width="788" alt="CleanShot 2023-02-12 at 19 56 30@2x" src="https://user-images.githubusercontent.com/273880/218367071-50e1376f-3df9-455d-843d-fd67c9449ef7.png">

```bash
Completed wave 61. Wrote mutations to 1 file.
Starting wave 62...

Error in /Users/felixsargent/src/hiring/resume-ranker-frontend/mysite/app/react/src/views/atsIntegrationSettings/exportSection.tsx at node '(prev) => new Set(prev.add(key))' (position 4481):
        Error: Could not find source file: '/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/lib.es2015.collection.d.ts'.
            at getValidSourceFile (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/typescript.js:169218:29)
            at Object.findReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/typescript.js:169701:117)
            at findRelevantNodeReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/references.js:43:56)
            at Object.findRelevantNodeReferencesAsNodes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/references.js:16:24)
            at FileInfoCache.getNodeReferencesAsNodes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/FileInfoCache.js:38:39)
            at updateAssignedTypesForReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/getPropsUsageTypes.js:50:10)
            at Object.getPropsUsageTypes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/getPropsUsageTypes.js:36:13)
            at visitReactComponentNode (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/index.js:23:57)
            at tryGetMutation (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/collectMutationsFromNodes.js:46:16)
            at visitNode (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/collectMutationsFromNodes.js:33:30)



Error in /Users/felixsargent/src/hiring/resume-ranker-frontend/mysite/app/react/src/views/atsIntegrationSettings/exportSection.tsx at node '(prev) => new Set(prev.add("mailDropAddress"))' (position 4929):
        Error: Could not find source file: '/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/lib.es2015.collection.d.ts'.
            at getValidSourceFile (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/typescript.js:169218:29)
            at Object.findReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typescript/lib/typescript.js:169701:117)
            at findRelevantNodeReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/references.js:43:56)
            at Object.findRelevantNodeReferencesAsNodes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/references.js:16:24)
            at FileInfoCache.getNodeReferencesAsNodes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/shared/FileInfoCache.js:38:39)
            at updateAssignedTypesForReferences (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/getPropsUsageTypes.js:50:10)
            at Object.getPropsUsageTypes (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/getPropsUsageTypes.js:36:13)
            at visitReactComponentNode (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromUses/index.js:23:57)
            at tryGetMutation (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/collectMutationsFromNodes.js:46:16)
            at visitNode (/Users/felixsargent/.npm/_npx/42ab35185b79194c/node_modules/typestat/src/mutators/collectMutationsFromNodes.js:33:30)


Completed wave 62. Wrote mutations to 1 file.
Starting wave 63...
Completed wave 63. Wrote mutations to 1 file.
It looks like TypeStat has ended up in an infinite loop.

Bailing out of applying more mutations.

Please file an issue to help us fix the bug for you:

https://github.com/JoshuaKGoldberg/TypeStat

Finished options object 2 of 2.
```

### Questions?

I'm not sure what it means, but it didn't finish! Anything I can do to make this happier?

**Comment by JoshuaKGoldberg** [comment]
Thanks for filing @fsargent! Per the _Bug_ issue template in this repo: Please paste a link to a repository, Gist, or other means of reproducing your error here. That must include your typestat.json file and any source files relevant to the issue.

I can't help you without being able to see the code you're running on! But I'd love to help.

**Comment by JoshuaKGoldberg** [comment]
@fsargent I'm going to go ahead and close this issue as I have no way of reproducing the crash or helping you with it. Let me know if there's any more info you can provide, and I can always take a deeper look!
