### ISSUE TITLE
extends in tsconfig.json not working

### ISSUE THREAD

**Issue by gutenye** [JoshuaKGoldberg/TypeStat#1306]
### 🐛 Bug Report

-   TypeStat version: 0.7.2
-   TypeScript version: 5.1.6
-   Node version: v16.18.0

#### Actual Behavior

```
Error: ENOENT: no such file or directory, stat 'node_modules/@tsconfig/node16/tsconfig.json/package.json'
```

The correct file should be 'node_modules/@tsconfig/node16/tsconfig.json'

#### Expected Behavior

Run without an error

#### Reproduction

```
vi tsconfig.json
{
	"extends": "@tsconfig/node16/tsconfig.json",
	..
}

npx typestat
npx typestat --config typestat.json
```

```ts
// typestat.json
{
    "files": {
        "renameExtensions": false
    },
    "fixes": {
        "incompleteTypes": true,
        "missingProperties": true,
        "noImplicitAny": true
    },
    "cleanups": {
        "suppressTypeErrors": true
    },
    "include": [
        "src/**/*.{js,jsx}"
    ],
    "project": "./tsconfig.json"
}
```

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for trying out TypeStat and filing an issue! I can't reproduce locally with those two files though. Is there a standalone gist, repo, or other set-of-code-files you can share that does demonstrate the issue?

**Comment by gutenye** [comment]
try this tsconfig.json 

```
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "include": [
    "src/**/*"
  ]
}
```

**Comment by JoshuaKGoldberg** [comment]
A more full stack locally:

```plaintext


Error: ENOTDIR: not a directory, stat '/Users/josh/repos/typestattemp/node_modules/@tsconfig/node16/tsconfig.json/package.json'
    at Object.statSync (node:fs:1620:3)
    at Object.<anonymous> (/Users/josh/repos/TypeStat/node_modules/graceful-fs/polyfills.js:319:16)
    at Object.fileExists (/Users/josh/repos/TypeStat/src/options/parseRawCompilerOptions.js:52:42)
    at getPackageJsonInfo (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40354:33)
    at loadModuleFromSpecificNodeModulesDirectory (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40997:23)
    at loadModuleFromImmediateNodeModulesDirectory (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40974:29)
    at /Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40962:33
    at forEachAncestorDirectory (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:6971:22)
    at lookup (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40956:14)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/Users/josh/repos/TypeStat/node_modules/typescript/lib/typescript.js:40953:14)
josh ~/repos/typestattemp $ 
```
