### ISSUE TITLE
languageService.getCodeFixesAtPosition error: Debug Failure. False expression: Token end is child end

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/TypeStat#277]
Top bit of stack:

```
Error in webpack/assets/javascripts/platform/libs/__tests__/workspace-test.tsx at node 'ws' (position 800):
	Error: Debug Failure. False expression: Token end is child end
	    at processChildNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109755:34)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109702:21
```

<details><summary>Full stack trace from <code>Error.stackTraceLimit = Infinity</code></summary>
<p>

```python
Error in webpack/assets/javascripts/platform/libs/__tests__/workspace-test.tsx at node 'ws' (position 800):
	Error: Debug Failure. False expression: Token end is child end
	    at processChildNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109755:34)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109702:21
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16507:24)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16585:21)
	    at processNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109701:20)
	    at processChildNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109761:21)
	    at processChildNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109812:48)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109704:21
	    at visitNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16512:24)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16647:24)
	    at processNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109701:20)
	    at formatSpanWorker (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109519:17)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109483:140
	    at Object.getFormattingScanner (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:108289:23)
	    at Object.formatNodeGivenIndentation (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:109483:31)
	    at getFormattedTextOfNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111487:45)
	    at format (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111465:52)
	    at computeNewText (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111468:23)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111438:89
	    at Array.map (<anonymous>)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111437:50
	    at Array.map (<anonymous>)
	    at Object.getTextChangesFromChanges (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111423:86)
	    at ChangeTracker.getChanges (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111393:45)
	    at Function.ChangeTracker.with (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:110936:32)
	    at Object.getCodeActions (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:112275:64)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111921:121
	    at Object.flatMap (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:563:25)
	    at Object.getFixes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:111921:23)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:121570:35
	    at Object.flatMap (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:563:25)
	    at Object.getCodeFixesAtPosition (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:121568:23)
	    at getNoImplicitAnyCodeFixes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutations/codeFixes/noImplicitAny.js:42:142)
	    at Object.exports.getNoImplicitAnyMutations (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutations/codeFixes/noImplicitAny.js:30:23)
	    at visitVariableDeclaration (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/builtIn/fixNoImplicitAny/fixNoImplicitAnyVariableDeclarations/index.js:29:32)
	    at tryGetMutation (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:31:16)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:19:30)
	    at visitNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16516:30)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16751:24)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16507:24)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16749:21)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16516:30)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16742:24)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16507:24)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16637:21)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16516:30)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16696:21)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16507:24)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16753:24)
	    at visitNode (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:24:12)
	    at visitNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16516:30)
	    at Object.forEachChild (/Users/joshgoldberg/Codecademy-dev/repos/typestat/node_modules/typescript/lib/typescript.js:16744:24)
	    at Object.exports.collectMutationsFromNodes (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/collectMutationsFromNodes.js:26:8)
	    at exports.fixNoImplicitAnyVariableDeclarations (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/builtIn/fixNoImplicitAny/fixNoImplicitAnyVariableDeclarations/index.js:18:40)
	    at Object.exports.findFirstMutations (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/shared/runtime.js:7:28)
	    at exports.fixNoImplicitAny (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/mutators/builtIn/fixNoImplicitAny/index.js:8:17)
	    at Object.exports.findFirstMutations (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/shared/runtime.js:7:28)
	    at Object.<anonymous> (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/findMutationsInFile.js:23:31)
	    at Generator.next (<anonymous>)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/findMutationsInFile.js:7:71
	    at new Promise (<anonymous>)
	    at __awaiter (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/findMutationsInFile.js:3:12)
	    at Object.exports.findMutationsInFile (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/findMutationsInFile.js:20:44)
	    at Object.<anonymous> (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/providers/createCoreMutationsProvider.js:48:64)
	    at Generator.next (<anonymous>)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/providers/createCoreMutationsProvider.js:7:71
	    at new Promise (<anonymous>)
	    at __awaiter (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/providers/createCoreMutationsProvider.js:3:12)
	    at Array.<anonymous> (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/providers/createCoreMutationsProvider.js:34:18)
	    at Object.<anonymous> (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:25:47)
	    at Generator.next (<anonymous>)
	    at /Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:7:71
	    at new Promise (<anonymous>)
	    at __awaiter (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:3:12)
	    at multiProvider (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:19:33)
	    at Object.<anonymous> (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:28:20)
	    at Generator.next (<anonymous>)
	    at fulfilled (/Users/joshgoldberg/Codecademy-dev/repos/typestat/src/runtime/createProviderFromProviders.js:4:58)
	    at <anonymous>
```

</p>
</details>

This is coming from the `request.languageService.getCodeFixesAtPosition` call in `noImplicitAny.ts`. I can use the TS language server in VS Code to get fixes on the `ws` node so I don't know why this is failing...

**Comment by devinrhode2** [comment]
Not sure if this is same situation, but, 
given:
```tsx
import Box from "@mui/material/Box";

import AutomatedMessage from "./AutomatedMessage";

function AppendedMessage(props) {
  const getDescription = () => {
    return (
      <Box margin-bottom="40px">
        <p>
          This Appended Message will be sent at the bottom of every text message
          any user sends to any Contact. It will apply to all users on this
          account.
        </p>
        <p>
          This is a good place to put any information required by your company
          to appear on every text message sent. Please keep in mind that the
          character limit is 160 and that individual users may still have their
          own Signature enabled.
        </p>
      </Box>
    );
  };

  return (
    <AutomatedMessage
      {...props}
      descriptionText={getDescription}
      type="appended"
    />
  );
}

export default AppendedMessage;
```

I'm seeing:
```
Error in /Users/devinrhode2/repos/textus/tess3/ui/app/features/AccountSettings/components/AppendedMessage.tsx at node 'props' (position 115):
        Error: Debug Failure. False expression.
            at consumeTokenAndAdvanceScanner (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147602:30)
            at processChildNode (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147508:25)
            at /Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147455:21
            at visitNode (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:30665:24)
            at Object.forEachChild (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:30758:21)
            at processNode (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147454:20)
            at processChildNode (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147525:21)
            at processChildNodes (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147579:48)
            at /Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:147457:21
            at visitNodes (/Users/devinrhode2/repos/tess-app/ui/node_modules/typescript/lib/typescript.js:30670:24)
```

with current/latest typestat, and this typestat.json:
```
[
  {
    "include": ["app/**/*.{ts,tsx}"],
    "fixes": {
      "incompleteTypes": false,
      "noImplicitAny": true,
      "inferableTypes": true,
      "noImplicitThis": true,
      "missingProperties": true
    },
    "projectPath": "./tsconfig.json"
  }
]
```

BTW do the compilerOptions in tsconfig have any effect?

**Comment by JoshuaKGoldberg** [comment]
@devinrhode2 that's a new situation; the message from the error is different. Could you please file a new issue with a full reproduction link? I can't reproduce from just the code snippet posted. We'll need at least your `typestat.json`, `package.json`, `tsconfig.json`, and `source file contents.

> BTW do the compilerOptions in tsconfig have any effect?

They do, yes. They're used to create the backing compiler services that power type information in mutators.

---

I can't repro the OP and don't have access to the repo it refers to, so I'll go ahead and close this issue as non-actionable. It's been 3+ years 😄.
